version: '3.8'
services:
   web:
       build:
         context: .
         dockerfile: Dockerfile
       container_name: dZENcode_test
       volumes:
         - .:/SPA-app
       command: python manage.py runserver localhost:8000
       ports:
           - 8000:8000